### PR TITLE
feat(raritiesWithOracle): Add rarities with oracle handler

### LINKED ISSUE #56: Update collectionFee to get the price in mana from the contract instead of the rarity
https://github.com/decentraland/collections-graph/pull/51

This pr is missing that after the block where rarities pegged to the usd is deployed, the collection fee should be determined by the contract in the mana price in that block instead of the rarity price.

This is because the rarity price was in mana previously and now is in usd, making the value useless or inappropriate.

### PR DESCRIPTION
**Pull request by fzavalia**
Closes #56

### CODE REVIEW

**Comment by fzavalia** [comment]
In draft until deployed to https://thegraph.com/hosted-service/subgraph/decentraland/collections-matic-mainnet

**Review by cazala — CHANGES_REQUESTED** [review]
I'm leaving this here so we don't lose track of it, as discussed here: https://github.com/decentraland/collections-graph/pull/55#discussion_r880665476

We should update the `item.creationFee` (which is set here: https://github.com/decentraland/collections-graph/blob/6fe1efd47b2588435a49e9466b4e42dff9468ee3/src/handlers/collection.ts#L112) to be converted to MANA after the block on which the oracle goes live.

**Comment by fzavalia** [comment]
> I'm leaving this here so we don't lose track of it, as discussed here: https://github.com/decentraland/collections-graph/pull/55#discussion_r880665476
> 
> We should update the `item.creationFee` (which is set here: https://github.com/decentraland/collections-graph/blob/6fe1efd47b2588435a49e9466b4e42dff9468ee3/src/handlers/collection.ts#L112) to be converted to MANA after the block on which the oracle goes live.

https://github.com/decentraland/collections-graph/issues/56 I've created this issue for it

**Comment by fzavalia** [comment]
@cazala Updated how the collectionFee is set to keep in mind that it is now converted from USD

**Comment by fzavalia** [comment]
@cazala That change is [here](https://github.com/decentraland/collections-graph/pull/51/files#diff-4e8a1e856f0e0e57ed5b2a1a38c8c730591c763d55867980be405eb5ddede665R124)

**Review by cazala — APPROVED** [review]

**Comment by fzavalia** [comment]
New things for the reviewer:

First I though we would have no issues deploying the graph without affecting current usability. However, as prices were updated with the raritities contract event, once the prices were set in the new contract, they would be reflected in the creationFee when publishing collections, and metrics would be affected.

To prevent this, rarities will be updated/created when the rarities contract is changed in the collection manager. Rarity events will only update the stored entities when the rarity contract sending the event is the one set in the collection manager.

**Review by cazala — APPROVED** [review]

**Pull request merged**
